### PR TITLE
Some refactoring

### PR DESCRIPTION
**Pull request by dcolish**
Hi,

I've started to use porkchop at work and I've made a few changes. Most of the changes are simple refactors for simplification. The largest refactor is how the plugins are loaded. I've removed the use of **class** and instead use instances of the respective classes. I've also added a little utility function for testing plugins. 

One thing I'm unsure of is how to hand the .gitmodules file. I'm thinking it should be a local file and not part of the checked in code, but that might have side effects. I'm not very familiar with all the inner workings of git submodules.

Thoughts and comments welcome,

Dan

### CODE REVIEW

**Comment by ohlol** [comment]
Hey, thanks for the pull request. I like what you've got but it's not working for me. I'm getting an exception:

```
  File "/home/scott/.virtualenvs/porkchop/local/lib/python2.7/site-packages/porkchop-0.7.3-py2.7.egg/porkchop/plugin.py", line 108, in load_plugins
    plugins[module_name] = plugin_(config_file)
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by dcolish** [comment]
Ah, it looks like you're using test.py as the plugin here. That plugin overrides PorkchopPlugin.**init** with an **init** which only takes one arg.

**Comment by dcolish** [comment]
How do you feel about a post_init hook to manage the config load so **init** can be overridden?

**Comment by dcolish** [comment]
Ok I've moved config loading to post init. I'll think more about how useful run hooks in plugins.

**Comment by ohlol** [comment]
Oh, duh. Completely forgot about that.

Pretty sure those should be calling super()

**Comment by ohlol** [comment]
Hmm, now that I htink about it, it feels like load_config should really happen in **init**()

**Comment by dcolish** [comment]
Yes, but if you forget to call super in your subclass the plugin would have the same odd failure case. This protects the core loading of the config from bad init's.

**Comment by dcolish** [comment]
Of course with the **init** failing to call super, you'll also lose the setting of refresh_interval and force_refresh. That will probably cause some errors down the road too.

**Comment by dcolish** [comment]
I think you're right about having the config load in **init**. I like the idea of a post_config hook for users to use for modifying the class instance. If users do subclass, they really should be expected to follow the **init** api setup in the baseclass or provide defaults for extra args.

**Pull request closed without merging**
